# config/packages/security.yaml

security:
  enable_authenticator_manager: true
  providers:
    app_user_provider:
      name: app_user_provider
      entity:
        class: TekosInteractive\SaaUserBundle\Domain\Entities\UserCredential
  firewalls:
    main:
      anonymous: true
    api:
      pattern: ^/api
      stateless: true
      provider: 'app_user_provider'
      jwt: ~
  access_control:
    - { path: ^/api, roles: IS_AUTHENTICATED_ANONYMOUSLY }